export const PERMISSIONS = {
  WORKSPACE_UPDATE: "WORKSPACE_UPDATE",
  WORKSPACE_DELETE: "WORKSPACE_DELETE",
  WORKSPACE_MANAGE_MEMBERS: "WORKSPACE_MANAGE_MEMBERS",
  WORKSPACE_MANAGE_ROLES: "WORKSPACE_MANAGE_ROLES",
  WORKSPACE_VIEW_ALL_PROJECTS: "WORKSPACE_VIEW_ALL_PROJECTS",
  WORKSPACE_VIEW_ANALYTICS: "WORKSPACE_VIEW_ANALYTICS",
  WORKSPACE_EXPORT_DATA: "WORKSPACE_EXPORT_DATA",

  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_VIEW: "PROJECT_VIEW",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  PROJECT_DELETE: "PROJECT_DELETE",
  PROJECT_MANAGE_MEMBERS: "PROJECT_MANAGE_MEMBERS",
  PROJECT_MANAGE_ROLES: "PROJECT_MANAGE_ROLES",
  PROJECT_VIEW_ANALYTICS: "PROJECT_VIEW_ANALYTICS",

  SPRINT_CREATE: "SPRINT_CREATE",
  SPRINT_UPDATE: "SPRINT_UPDATE",
  SPRINT_DELETE: "SPRINT_DELETE",
  SPRINT_COMPLETE: "SPRINT_COMPLETE",

  TASK_CREATE: "TASK_CREATE",
  TASK_UPDATE_FULL: "TASK_UPDATE_FULL",
  TASK_UPDATE_STATUS: "TASK_UPDATE_STATUS",
  TASK_ASSIGN: "TASK_ASSIGN",
  TASK_DELETE: "TASK_DELETE",

  EVENT_CREATE: "EVENT_CREATE",
  EVENT_UPDATE: "EVENT_UPDATE",
  EVENT_DELETE: "EVENT_DELETE",

  RISK_VIEW: "RISK_VIEW",
  RISK_CREATE: "RISK_CREATE",
  RISK_UPDATE: "RISK_UPDATE",
  RISK_DELETE: "RISK_DELETE",

  COMMENT_CREATE: "COMMENT_CREATE",
  COMMENT_DELETE: "COMMENT_DELETE",

  FILE_UPLOAD: "FILE_UPLOAD",
  FILE_DELETE: "FILE_DELETE",
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;