import { DummyProject, ProjectStatus } from "./types";

export const dummyProjects: DummyProject[] = [
  {
    id: 'project_001',
    workspaceId: 'workspace_001',
    name: 'Website Redesign',
    description: 'Complete redesign of company website with modern UI/UX and improved performance',
    imageUrl: null,
    startDate: new Date('2024-01-15'),
    dueDate: new Date('2024-06-30'),
    completedAt: null,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-20'),
    createdBy: 'user_001',
    projectManagerId: 'user_002',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 65,
    budget: 50000,
    totalTasks: 45,
    totalSegments: 8,
    completedTasks: 28,
    members: 8
  },
  {
    id: 'project_002',
    workspaceId: 'workspace_001',
    name: 'Mobile App Development',
    description: 'Build a cross-platform mobile application for customer engagement and support',
    imageUrl: null,
    startDate: new Date('2024-02-01'),
    dueDate: new Date('2024-08-15'),
    completedAt: null,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-04-10'),
    createdBy: 'user_001',
    projectManagerId: 'user_003',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 40,
    budget: 75000,
    totalTasks: 62,
    totalSegments: 12,
    completedTasks: 24,
    members: 12
  },
  {
    id: 'project_003',
    workspaceId: 'workspace_001',
    name: 'E-commerce Platform',
    description: 'Develop a full-featured online shopping platform with payment integration',
    imageUrl: null,
    startDate: new Date('2023-11-01'),
    dueDate: new Date('2024-03-31'),
    completedAt: new Date('2024-03-28'),
    createdAt: new Date('2023-10-20'),
    updatedAt: new Date('2024-03-28'),
    createdBy: 'user_002',
    projectManagerId: 'user_001',
    projectStatus: ProjectStatus.COMPLETED,
    progress: 100,
    budget: 100000,
    totalTasks: 85,
    totalSegments: 15,
    completedTasks: 85,
    members: 15
  },
  {
    id: 'project_004',
    workspaceId: 'workspace_001',
    name: 'CRM System Upgrade',
    description: 'Upgrade and migrate existing CRM to new version with enhanced features',
    imageUrl: null,
    startDate: new Date('2024-03-01'),
    dueDate: new Date('2024-07-15'),
    completedAt: null,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-05-05'),
    createdBy: 'user_003',
    projectManagerId: 'user_002',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 30,
    budget: 60000,
    totalTasks: 38,
    totalSegments: 6,
    completedTasks: 11,
    members: 6
  },
  {
    id: 'project_005',
    workspaceId: 'workspace_001',
    name: 'Analytics Dashboard',
    description: 'Create real-time analytics dashboard for business metrics and reporting',
    imageUrl: null,
    startDate: new Date('2024-04-01'),
    dueDate: new Date('2024-09-30'),
    completedAt: null,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-05-15'),
    createdBy: 'user_004',
    projectManagerId: 'user_005',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 20,
    budget: 45000,
    totalTasks: 28,
    totalSegments: 4,
    completedTasks: 5,
    members: 4
  },
  {
    id: 'project_006',
    workspaceId: 'workspace_002',
    name: 'API Integration',
    description: 'Integrate third-party APIs for payment processing and shipping',
    imageUrl: null,
    startDate: new Date('2023-12-01'),
    dueDate: new Date('2024-02-15'),
    completedAt: new Date('2024-02-10'),
    createdAt: new Date('2023-11-20'),
    updatedAt: new Date('2024-02-10'),
    createdBy: 'user_005',
    projectManagerId: 'user_002',
    projectStatus: ProjectStatus.COMPLETED,
    progress: 100,
    budget: 30000,
    totalTasks: 22,
    totalSegments: 3,
    completedTasks: 22,
    members: 3
  },
  {
    id: 'project_007',
    workspaceId: 'workspace_002',
    name: 'Security Audit',
    description: 'Conduct comprehensive security audit and implement improvements',
    imageUrl: null,
    startDate: new Date('2024-05-01'),
    dueDate: new Date('2024-10-31'),
    completedAt: null,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-06-10'),
    createdBy: 'user_002',
    projectManagerId: 'user_003',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 15,
    budget: 35000,
    totalTasks: 18,
    totalSegments: 5,
    completedTasks: 2,
    members: 5
  },
  {
    id: 'project_008',
    workspaceId: 'workspace_002',
    name: 'Documentation Portal',
    description: 'Build internal documentation portal for team knowledge sharing',
    imageUrl: null,
    startDate: new Date('2024-02-15'),
    dueDate: new Date('2024-05-30'),
    completedAt: new Date('2024-05-25'),
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-05-25'),
    createdBy: 'user_003',
    projectManagerId: 'user_004',
    projectStatus: ProjectStatus.COMPLETED,
    progress: 100,
    budget: 25000,
    totalTasks: 32,
    totalSegments: 7,
    completedTasks: 32,
    members: 7
  },
  {
    id: 'project_009',
    workspaceId: 'workspace_002',
    name: 'Payment Gateway Integration',
    description: 'Integrate new payment gateway with fraud detection system',
    imageUrl: null,
    startDate: new Date('2025-10-01'),
    dueDate: new Date('2025-12-10'),
    completedAt: null,
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2025-12-15'),
    createdBy: 'user_002',
    projectManagerId: 'user_001',
    projectStatus: ProjectStatus.OVER_DUE,
    progress: 85,
    budget: 40000,
    totalTasks: 35,
    totalSegments: 5,
    completedTasks: 30,
    members: 5
  },
  {
    id: 'project_010',
    workspaceId: 'workspace_002',
    name: 'Server Migration Project',
    description: 'Migrate servers to new data center with zero downtime',
    imageUrl: null,
    startDate: new Date('2025-11-15'),
    dueDate: new Date('2025-12-05'),
    completedAt: null,
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-12-18'),
    createdBy: 'user_003',
    projectManagerId: 'user_004',
    projectStatus: ProjectStatus.OVER_DUE,
    progress: 75,
    budget: 60000,
    totalTasks: 42,
    totalSegments: 8,
    completedTasks: 32,
    members: 8
  },
  {
    id: 'project_011',
    workspaceId: 'workspace_003',
    name: 'Q4 Marketing Campaign',
    description: 'End of year marketing campaign across all channels',
    imageUrl: null,
    startDate: new Date('2025-10-10'),
    dueDate: new Date('2025-11-30'),
    completedAt: null,
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-12-10'),
    createdBy: 'user_005',
    projectManagerId: 'user_002',
    projectStatus: ProjectStatus.OVER_DUE,
    progress: 90,
    budget: 75000,
    totalTasks: 28,
    totalSegments: 6,
    completedTasks: 25,
    members: 6
  },
  {
    id: 'project_012',
    workspaceId: 'workspace_003',
    name: 'Client Portal Launch',
    description: 'Launch new client portal with dashboard and reporting',
    imageUrl: null,
    startDate: new Date('2025-11-01'),
    dueDate: new Date('2025-12-20'),
    completedAt: null,
    createdAt: new Date('2025-10-25'),
    updatedAt: new Date('2025-12-19'),
    createdBy: 'user_001',
    projectManagerId: 'user_003',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 95,
    budget: 55000,
    totalTasks: 50,
    totalSegments: 7,
    completedTasks: 48,
    members: 7
  },
  {
    id: 'project_013',
    workspaceId: 'workspace_003',
    name: 'Mobile App Beta Testing',
    description: 'Beta testing phase for new mobile application',
    imageUrl: null,
    startDate: new Date('2025-11-20'),
    dueDate: new Date('2025-12-22'),
    completedAt: null,
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2025-12-19'),
    createdBy: 'user_004',
    projectManagerId: 'user_005',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 80,
    budget: 30000,
    totalTasks: 25,
    totalSegments: 4,
    completedTasks: 20,
    members: 4
  },
  {
    id: 'project_014',
    workspaceId: 'workspace_003',
    name: 'Annual Report Preparation',
    description: 'Prepare and publish annual company report',
    imageUrl: null,
    startDate: new Date('2025-12-01'),
    dueDate: new Date('2025-12-23'),
    completedAt: null,
    createdAt: new Date('2025-11-28'),
    updatedAt: new Date('2025-12-19'),
    createdBy: 'user_002',
    projectManagerId: 'user_001',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 70,
    budget: 20000,
    totalTasks: 18,
    totalSegments: 3,
    completedTasks: 13,
    members: 3
  },
  {
    id: 'project_015',
    workspaceId: 'workspace_003',
    name: 'Inventory System Update',
    description: 'Update inventory management system with new features',
    imageUrl: null,
    startDate: new Date('2025-11-25'),
    dueDate: new Date('2025-12-27'),
    completedAt: null,
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2025-12-19'),
    createdBy: 'user_003',
    projectManagerId: 'user_004',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 60,
    budget: 45000,
    totalTasks: 30,
    totalSegments: 5,
    completedTasks: 18,
    members: 5
  },
  {
    id: 'project_016',
    workspaceId: 'workspace_004',
    name: 'Employee Training Program',
    description: 'Quarterly employee training and development program',
    imageUrl: null,
    startDate: new Date('2025-12-05'),
    dueDate: new Date('2025-12-31'),
    completedAt: null,
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-19'),
    createdBy: 'user_005',
    projectManagerId: 'user_002',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 40,
    budget: 35000,
    totalTasks: 22,
    totalSegments: 6,
    completedTasks: 9,
    members: 6
  },
  {
    id: 'project_017',
    workspaceId: 'workspace_004',
    name: 'AI Chatbot Implementation',
    description: 'Implement AI-powered chatbot for customer support',
    imageUrl: null,
    startDate: new Date('2026-01-15'),
    dueDate: new Date('2026-03-31'),
    completedAt: null,
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2025-12-19'),
    createdBy: 'user_001',
    projectManagerId: 'user_003',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 10,
    budget: 80000,
    totalTasks: 45,
    totalSegments: 8,
    completedTasks: 5,
    members: 8
  },
  {
    id: 'project_018',
    workspaceId: 'workspace_004',
    name: 'Database Optimization',
    description: 'Optimize database performance and implement indexing',
    imageUrl: null,
    startDate: new Date('2025-10-01'),
    dueDate: new Date('2025-11-30'),
    completedAt: new Date('2025-11-25'),
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2025-11-25'),
    createdBy: 'user_004',
    projectManagerId: 'user_005',
    projectStatus: ProjectStatus.COMPLETED,
    progress: 100,
    budget: 30000,
    totalTasks: 20,
    totalSegments: 4,
    completedTasks: 20,
    members: 4
  },
  {
    id: 'project_019',
    workspaceId: 'workspace_004',
    name: 'Website Performance Audit',
    description: 'Audit and improve website loading speed and performance',
    imageUrl: null,
    startDate: new Date('2025-11-01'),
    dueDate: new Date('2025-12-10'),
    completedAt: new Date('2025-12-08'),
    createdAt: new Date('2025-10-25'),
    updatedAt: new Date('2025-12-08'),
    createdBy: 'user_002',
    projectManagerId: 'user_001',
    projectStatus: ProjectStatus.COMPLETED,
    progress: 100,
    budget: 25000,
    totalTasks: 15,
    totalSegments: 3,
    completedTasks: 15,
    members: 3
  },
  {
    id: 'project_020',
    workspaceId: 'workspace_004',
    name: 'Mobile App UI/UX Revamp',
    description: 'Redesign mobile app interface with new user experience',
    imageUrl: null,
    startDate: new Date('2025-12-15'),
    dueDate: new Date('2026-02-28'),
    completedAt: null,
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2025-12-19'),
    createdBy: 'user_003',
    projectManagerId: 'user_004',
    projectStatus: ProjectStatus.ACTIVE,
    progress: 5,
    budget: 50000,
    totalTasks: 35,
    totalSegments: 6,
    completedTasks: 2,
    members: 6
  }
];