import { Task, TaskStatus, TaskType, TaskPriority } from "@/features/tasks/types";

export const dummyTasks: Task[] = [
  {
    id: 'task_001',
    workspaceId: 'workspace_001',
    projectId: 'project_001',
    segmentId: 'segment_001',
    name: 'Homepage Wireframe Design',
    description: 'Create wireframe for homepage layout with user flow',
    budget: 5000,
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-01-20'),
    assigneeId: 'user_001',
    assignedById: 'user_002',
    taskStatus: TaskStatus.DONE,
    taskType: TaskType.TASK,
    taskPriority: TaskPriority.HIGH,
    effortPoints: 5,
    progress: 100,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-20'),
    position: 1,
    blockedBy: '',
    blockingTo: 'task_002'
  },
  {
    id: 'task_002',
    workspaceId: 'workspace_001',
    projectId: 'project_001',
    segmentId: 'segment_001',
    name: 'Product Page Design',
    description: 'Design product listing and detail pages with mobile responsiveness',
    budget: 8000,
    startDate: new Date('2024-01-18'),
    endDate: new Date('2024-01-25'),
    assigneeId: 'user_002',
    assignedById: 'user_001',
    taskStatus: TaskStatus.DONE,
    taskType: TaskType.TASK,
    taskPriority: TaskPriority.MEDIUM,
    effortPoints: 8,
    progress: 100,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-25'),
    position: 2,
    blockedBy: 'task_001',
    blockingTo: 'task_004'
  },
  {
    id: 'task_003',
    workspaceId: 'workspace_001',
    projectId: 'project_001',
    segmentId: 'segment_001',
    name: 'Mobile Responsive Design',
    description: 'Ensure all designs are mobile responsive across devices',
    budget: 12000,
    startDate: new Date('2024-01-22'),
    endDate: new Date('2024-01-28'),
    assigneeId: 'user_006',
    assignedById: 'user_001',
    taskStatus: TaskStatus.DONE,
    taskType: TaskType.FEATURE,
    taskPriority: TaskPriority.HIGH,
    effortPoints: 10,
    progress: 100,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-28'),
    position: 3,
    blockedBy: 'task_001',
    blockingTo: 'task_005'
  },

];